# vault configurations
[meta]
    # friendly name
    title =                 "nwgui-assets"
    # contributors
    author =                ""
    # version
    version =               "1.2.2"

# asset pack configurations
[asset_pack]
    # asset packs requirements
    assets_requirements = [
                            
    ]

# unreal engine configurations
[unreal]
    # unreal engine folder - the exact name of the root folder inside Content/ or Plugin/ used in Unreal
    unreal_folder =         "advanced-widgets"
    # unreal engine version - unreal version this asset pack was compiled on
    unreal_version =        "5.3.1"
    # whether this asset pack was created as a plugin content
    is_plugin_content =     true

# assets files
[assets]
    # maps
    [assets.maps]
        # MyMap = "MyFolder/MyAwesomeMap"
        # ...

    # static meshes
    [assets.static_meshes]
        # SM_Flower_01 = "MyFolder/SM_Awesome_Flower_01"
        # SM_Rock_01 = { path = "MyFolder/SM_Rock_01", my_tag = "something", thumbnail = "Thumbnails/SM_Rock_01.jpg" }
        # ...

    # skeletal meshes
    [assets.skeletal_meshes]
        # SK_Better_Man = "Characters/SK_BetterMan_03"
        # ...

    # sounds
    [assets.sounds]
        # A_Awesome_Music = "Sounds/A_Awesome_Music"
        # ...

    # animations
    [assets.animations]
        # A_Character_Jump = "Animations/A_Character_Jump"
        # ...

    # particles
    [assets.particles]
        # P_Big_Explosion = "Particles/P_Big_Explosion"
        # ...

    # materials
    [assets.materials]
        # M_Red_Textured = "Materials/M_Red_Textured"
        # ...

    # blueprints
    [assets.blueprints]
        AW_Border = { path = "Components/AW_Border", key = "AW_Border" }
        AW_Button = { path = "Components/AW_Button", key = "AW_Button" }
        AW_Canvas = { path = "Components/Panels/AW_Canvas", key = "AW_Canvas" }
        AW_CheckBox = { path = "Components/AW_CheckBox", key = "AW_CheckBox" }
        AW_ComboBox = { path = "Components/AW_ComboBox", key = "AW_ComboBox" }
        AW_EditableText = { path = "Components/AW_EditableText", key = "AW_EditableText" }
        AW_EditableTextMultiLine = { path = "Components/AW_EditableTextMultiLine", key = "AW_EditableTextMultiLine" }
        AW_GradientPanel = { path = "Components/Panels/AW_GradientPanel", key = "AW_GradientPanel" }
        AW_Grid = { path = "Components/Panels/AW_Grid", key = "AW_Grid" }
        AW_HorizontalBox = { path = "Components/Panels/AW_HorizontalBox", key = "AW_HorizontalBox" }
        AW_Image = { path = "Components/AW_Image", key = "AW_Image" }
        AW_InvalidationBox = { path = "Components/Panels/AW_InvalidationBox", key = "AW_InvalidationBox" }
        AW_Overlay = { path = "Components/Panels/AW_Overlay", key = "AW_Overlay" }
        AW_ProgressBar = { path = "Components/AW_ProgressBar", key = "AW_ProgressBar" }
        AW_RetainerBox = { path = "Components/Panels/AW_RetainerBox", key = "AW_RetainerBox" }
        AW_RichText = { path = "Components/AW_RichText", key = "AW_RichText" }
        AW_ScaleBox = { path = "Components/Panels/AW_ScaleBox", key = "AW_ScaleBox" }
        AW_ScrollBox = { path = "Components/Panels/AW_ScrollBox", key = "AW_ScrollBox" }
        AW_SizeBox = { path = "Components/Panels/AW_SizeBox", key = "AW_SizeBox" }
        AW_Slider = { path = "Components/AW_Slider", key = "AW_Slider" }
        AW_SpinBox = { path = "Components/AW_SpinBox", key = "AW_SpinBox" }
        AW_Text = { path = "Components/AW_Text", key = "AW_Text" }
        AW_Throbber = { path = "Components/AW_Throbber", key = "AW_Throbber" }
        AW_UniformGrid = { path = "Components/Panels/AW_UniformGridPanel", key = "AW_UniformGrid" }
        AW_VerticalBox = { path = "Components/Panels/AW_VerticalBox", key = "AW_VerticalBox" }
        AW_WidgetSwitcher = { path = "Components/Panels/AW_WidgetSwitcher", key = "AW_WidgetSwitcher" }
        AW_WrapBox = { path = "Components/Panels/AW_WrapBox", key = "AW_WrapBox" }
        BP_WidgetUtility = { path = "BP_WidgetUtility", key = "BP_WidgetUtility" }

    # other assets (for not yet categorized ones)
    [assets.others]
        # Some_Stuff = "Others/Some_Stuff"
        # ...
