# vault configurations
[meta]
    # friendly name
    title =                 "nwgui-assets"
    # contributors
    author =                ""
    # version
    version =               "1.0.1"

# asset pack configurations
[asset_pack]
    # asset packs requirements
    assets_requirements = [
                            
    ]

# unreal engine configurations
[unreal]
    # unreal engine folder - the exact name of the root folder inside Content/ or Plugin/ used in Unreal
    unreal_folder =         "advanced-widgets"
    # unreal engine version - unreal version this asset pack was compiled on
    unreal_version =        "5.1.0"
    # whether this asset pack was created as a plugin content
    is_plugin_content =     true

# assets files
[assets]
    # maps
    [assets.maps]
        # MyMap = "MyFolder/MyAwesomeMap"
        # ...

    # static meshes
    [assets.static_meshes]
        # SM_Flower_01 = "MyFolder/SM_Awesome_Flower_01"
        # ...

    # skeletal meshes
    [assets.skeletal_meshes]
        # SK_Better_Man = "Characters/SK_BetterMan_03"
        # ...

    # sounds
    [assets.sounds]
        # A_Awesome_Music = "Sounds/A_Awesome_Music"
        # ...

    # animations
    [assets.animations]
        # A_Character_Jump = "Animations/A_Character_Jump"
        # ...

    # particles
    [assets.particles]
        # P_Big_Explosion = "Particles/P_Big_Explosion"
        # ...

    # materials
    [assets.materials]
        # M_Red_Textured = "Materials/M_Red_Textured"
        # ...

    # blueprints
    [assets.blueprints]
        AW_Border = "Components/AW_Border"
        AW_Button = "Components/AW_Button"
        AW_Canvas = "Components/Panels/AW_Canvas"
        AW_CheckBox = "Components/AW_CheckBox"
        AW_ComboBox = "Components/AW_ComboBox"
        AW_EditableText = "Components/AW_EditableText"
        AW_EditableTextMultiLine = "Components/AW_EditableTextMultiLine"
        AW_GradientPanel = "Components/Panels/AW_GradientPanel"
        AW_Grid = "Components/Panels/AW_Grid"
        AW_HorizontalBox = "Components/Panels/AW_HorizontalBox"
        AW_Image = "Components/AW_Image"
        AW_Overlay = "Components/Panels/AW_Overlay"
        AW_ScrollBox = "Components/Panels/AW_ScrollBox"
        AW_SizeBox = "Components/Panels/AW_SizeBox"
        AW_Slider = "Components/AW_Slider"
        AW_SpinBox = "Components/AW_SpinBox"
        AW_Text = "Components/AW_Text"
        AW_Throbber = "Components/AW_Throbber"
        AW_UniformGrid = "Components/Panels/AW_UniformGridPanel"
        AW_VerticalBox = "Components/Panels/AW_VerticalBox"
        AW_WidgetSwitcher = "Components/Panels/AW_WidgetSwitcher"
        AW_WrapBox = "Components/Panels/AW_WrapBox"
        BP_WidgetUtility = "BP_WidgetUtility"

    # other assets (for not yet categorized ones)
    [assets.others]
        # Some_Stuff = "Others/Some_Stuff"
        # ...
